from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import zipfile
from contextlib import contextmanager
from dataclasses import asdict
from pathlib import Path, PurePosixPath
from typing import Any
from uuid import uuid4

from refract_pptx.models import load_task_spec
from refract_pptx.presentation import object_inventory
from refract_pptx.validation import validate_bundle

from .base import AdapterError, EmittedPackage, PackageFile, RunnerProfile

ADAPTER_ID = "desktop_base_task.v1"
EVALUATOR_ID = "refract.delta_progress.v2"
_RESERVED_PUBLIC_NAMES = {
    "build.json",
    "gt_inventory.json",
    "init_inventory.json",
    "plan.json",
    "provenance.json",
    "runtime.zip",
    "task_spec.json",
}
_RUNTIME_FILES = (
    "__init__.py",
    "models.py",
    "presentation/__init__.py",
    "presentation/inventory.py",
    "presentation/objects.py",
    "presentation/visual.py",
    "presentation/visual_mutation.py",
    "presentation/chart_style.py",
    "presentation/chart_workbook.py",
    "presentation/typography.py",
    "presentation/smartart.py",
    "evaluation/__init__.py",
    "evaluation/progress.py",
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _safe_relative(value: str, label: str) -> PurePosixPath:
    path = PurePosixPath(value.replace("\\", "/"))
    if path.is_absolute() or not path.parts or ".." in path.parts:
        raise AdapterError(f"{label} must stay inside its declared root: {value}")
    return path


def _copy_file(source: Path, target: Path) -> None:
    if source.is_symlink():
        raise AdapterError(f"symbolic links are not allowed in deployment assets: {source}")
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


@contextmanager
def _staging_directory(target: Path):
    staging = target.parent / f".{target.name}-{uuid4().hex}"
    staging.mkdir()
    try:
        yield staging
    finally:
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)


def _runtime_archive(target: Path) -> None:
    package_root = Path(__file__).resolve().parents[1]
    target.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(target, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for relative in _RUNTIME_FILES:
            source = package_root / relative
            if not source.is_file():
                raise AdapterError(f"runtime source is missing: {source}")
            payload = source.read_text(encoding="utf-8").replace("refract_pptx", "_refract_runtime")
            info = zipfile.ZipInfo(f"_refract_runtime/{relative}")
            info.date_time = (1980, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, payload.encode("utf-8"))


def _instruction(
    original: str,
    deck_vm_path: str,
    reference_vm_path: str,
    materials_vm_dir: str,
    has_materials: bool,
) -> str:
    lines = [
        original.strip(),
        "",
        f"The damaged presentation is open in WPS Presentation at `{deck_vm_path}`.",
        f"Use `{reference_vm_path}` as the visual reference.",
    ]
    if has_materials:
        lines.append(f"Additional supplied assets are in `{materials_vm_dir}`.")
    lines.extend(
        [
            "Repair the editable presentation rather than replacing slides with screenshots.",
            f"Save the final presentation in place at `{deck_vm_path}`.",
        ]
    )
    return "\n".join(lines)


def _task_source(constants: dict[str, Any]) -> str:
    class_name = "Task_" + re.sub(r"[^A-Za-z0-9_]", "_", constants["TASK_ID"])
    rows = "\n".join(f"{name} = {value!r}" for name, value in constants.items())
    return f'''"""Generated by REFRACT. Regenerate this module instead of editing it."""

from __future__ import annotations

import hashlib
import importlib
import json
import os
import shlex
import sys
import time
import urllib.parse
import zipfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

from desktop_env.task_base import BaseTask
from desktop_env.evaluators.getters import get_vm_command_line, get_vm_file

if TYPE_CHECKING:
    from desktop_env.controllers.setup import SetupController
    from desktop_env.desktop_env import DesktopEnv

{rows}

TASK_MODULE_DIR = Path(__file__).resolve().parent
TEST_ASSETS = (TASK_MODULE_DIR / HIDDEN_ASSETS_RELATIVE).resolve()


class AssetFetchError(RuntimeError):
    pass


def _sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _asset_url(remote_path: str) -> str:
    base = (os.environ.get(ASSET_BASE_ENV) or ASSET_BASE_URL).rstrip("/")
    if "://" not in base:
        return os.path.join(base, *remote_path.split("/"))
    quoted = "/".join(urllib.parse.quote(item, safe="") for item in remote_path.split("/"))
    return f"{{base}}/{{quoted}}"


def _fetch_assets(setup_controller: Any) -> None:
    files = [{{"url": _asset_url(remote), "path": vm_path}} for remote, vm_path, _ in FETCH]
    try:
        setup_controller.download(files)
        checks = " && ".join(
            "test \\\"$(sha256sum {{path}} | cut -d' ' -f1)\\\" = {{digest}}".format(
                path=shlex.quote(vm_path), digest=shlex.quote(expected)
            )
            for _, vm_path, expected in FETCH
        )
        setup_controller.execute(command=checks or "true", shell=True)
    except Exception as exc:
        raise AssetFetchError(
            f"task assets could not be fetched and verified: {{type(exc).__name__}}: {{exc}}"
        ) from exc


def _vm_command(env: Any, command: str, timeout: int = 60) -> str:
    result = get_vm_command_line(
        env, {{"command": ["bash", "-lc", command], "timeout": timeout}}
    )
    return str(result or "")


def _vm_sha256(env: Any, path: str) -> str:
    quoted = shlex.quote(path)
    output = _vm_command(
        env,
        f"if [ -f {{quoted}} ]; then sha256sum {{quoted}} | cut -d' ' -f1; "
        "else echo MISSING; fi",
        30,
    ).strip()
    if not output:
        raise RuntimeError("the runner returned no result for a VM filesystem check")
    value = output.splitlines()[-1]
    return "" if value == "MISSING" else value


def _persist_candidate(env: Any) -> dict[str, Any]:
    before = _vm_sha256(env, DECK_VM_PATH)
    evidence: dict[str, Any] = {{
        "disk_sha_before": before,
        "save_attempted": False,
    }}
    if before == INIT_SHA256:
        window = shlex.quote(DECK_NAME)
        script = (
            "export DISPLAY=${{DISPLAY:-:0}}; "
            f"if command -v xdotool >/dev/null 2>&1 && "
            f"xdotool search --name {{window}} windowactivate --sync >/dev/null 2>&1; then "
            "xdotool key ctrl+s; "
            "else python3 -c \\\"import pyautogui; pyautogui.hotkey('ctrl','s')\\\"; fi; "
            "sleep 4"
        )
        _vm_command(env, script, 30)
        evidence["save_attempted"] = True
    _vm_command(
        env,
        "pkill -f wpp || true; pkill -f wps || true; pkill -f soffice || true",
        30,
    )
    time.sleep(1)
    after = _vm_sha256(env, DECK_VM_PATH)
    evidence["disk_sha_after"] = after
    evidence["disk_changed"] = bool(after and after != INIT_SHA256)
    return evidence


def _scan_save_as(env: Any) -> tuple[list[tuple[str, str]], str]:
    stamp = shlex.quote(SETUP_STAMP)
    desktop = shlex.quote(DESKTOP_DIR)
    output = _vm_command(
        env,
        f"if [ ! -e {{stamp}} ]; then echo NO_STAMP; exit 0; fi; echo SCAN_READY; "
        f"find {{desktop}} /home/user -maxdepth 3 -type f -name '*.pptx' "
        f"-newer {{stamp}} -not -path {{shlex.quote(DECK_VM_PATH)}} -print0 2>/dev/null "
        "| xargs -0 -r sha256sum 2>/dev/null",
        60,
    )
    if not output.strip():
        raise RuntimeError("the runner returned no result for Save As discovery")
    if output.strip() == "NO_STAMP":
        return [], "setup stamp is missing; Save As recovery was not attempted"
    found: list[tuple[str, str]] = []
    seen: set[str] = set()
    for line in output.splitlines():
        if line.strip() == "SCAN_READY":
            continue
        digest, _, path = line.strip().partition(" ")
        path = path.strip()
        if len(digest) == 64 and path and path not in seen:
            seen.add(path)
            if digest != INIT_SHA256 and digest not in SUPPLIED_PPTX_SHA256:
                found.append((path, digest))
    return found, ""


def _candidate_file(env: Any, evidence: dict[str, Any]) -> tuple[str, str]:
    pinned_sha = evidence.get("disk_sha_after", "")
    if pinned_sha and pinned_sha != INIT_SHA256:
        local = get_vm_file(
            env, {{"path": DECK_VM_PATH, "dest": f"task_{{TASK_ID}}_result.pptx"}}
        )
        if not local or not os.path.isfile(local):
            raise RuntimeError(
                "the VM reported a changed result but the runner could not retrieve it"
            )
        return str(local), DECK_VM_PATH
    found, note = _scan_save_as(env)
    if note:
        evidence["save_as_note"] = note
    evidence["save_as_candidates"] = [path for path, _ in found]
    if len(found) != 1:
        return "", ""
    vm_path = found[0][0]
    local = get_vm_file(
        env, {{"path": vm_path, "dest": f"task_{{TASK_ID}}_save_as_result.pptx"}}
    )
    if not local or not os.path.isfile(local):
        raise RuntimeError("a unique Save As result was found but could not be retrieved")
    return str(local), vm_path


def _load_runtime() -> tuple[Any, Any, Any]:
    runtime = TEST_ASSETS / "runtime.zip"
    if not runtime.is_file() or _sha256_file(runtime) != HIDDEN_HASHES["runtime.zip"]:
        raise RuntimeError("the pinned evaluator runtime is missing or has changed")
    for name in ("plan.json", "init_inventory.json"):
        path = TEST_ASSETS / name
        if not path.is_file() or _sha256_file(path) != HIDDEN_HASHES[name]:
            raise RuntimeError(f"hidden evaluator asset is missing or has changed: {{name}}")
    runtime_text = str(runtime)
    if runtime_text not in sys.path:
        sys.path.insert(0, runtime_text)
    evaluation = importlib.import_module("_refract_runtime.evaluation")
    presentation = importlib.import_module("_refract_runtime.presentation")
    return (
        evaluation.evaluate_snapshots,
        presentation.object_inventory,
        presentation.deck_snapshot_from_dict,
    )


def _agent_failure(reason: str, evidence: dict[str, Any]) -> dict[str, Any]:
    return {{
        "evaluator": EVALUATOR_ID,
        "score": 0.0,
        "failure_reason": reason,
        "evidence": evidence,
    }}


class {class_name}(BaseTask):
    id = TASK_ID
    snapshot = SNAPSHOT
    instruction = INSTRUCTION
    source = SOURCE
    trajectory = "trajectories/"
    related_apps = RELATED_APPS
    platform = PLATFORM
    proxy = PROXY
    disable_vnc = DISABLE_VNC
    disable_recording = DISABLE_RECORDING
    intermediate_eval_safe = False
    volume_size = VOLUME_SIZE
    config = []
    user_simulator = None
    evaluator = None
    fixed_ip = False
    possibility_of_env_change = "low"
    instance_type = None
    image = None

    def setup(self, setup_controller: "SetupController", use_proxy: bool = False) -> None:
        paths = [DECK_VM_PATH, REFERENCE_VM_PATH, SETUP_STAMP]
        quoted = " ".join(shlex.quote(path) for path in paths)
        setup_controller.execute(command=f"rm -f {{quoted}}", shell=True)
        setup_controller.execute(
            command=f"rm -rf {{shlex.quote(MATERIALS_VM_DIR)}}", shell=True
        )
        if HAS_MATERIALS:
            setup_controller.execute(
                command=f"mkdir -p {{shlex.quote(MATERIALS_VM_DIR)}}", shell=True
            )
        _fetch_assets(setup_controller)
        setup_controller.execute(command=f"touch {{shlex.quote(SETUP_STAMP)}}", shell=True)
        setup_controller.execute(
            command=(
                "xdg-mime default wps-office-wpp.desktop "
                "application/vnd.openxmlformats-officedocument.presentationml.presentation "
                "2>/dev/null || true"
            ),
            shell=True,
        )
        setup_controller.launch(APPLICATION_COMMAND)

    def evaluate(self, env: "DesktopEnv") -> dict[str, Any]:
        evidence = _persist_candidate(env)
        candidate_path, vm_path = _candidate_file(env, evidence)
        evidence["scored_vm_path"] = vm_path
        if not candidate_path:
            return _agent_failure(
                "no saved result was found at the required path or as one unambiguous Save As file",
                evidence,
            )
        if not zipfile.is_zipfile(candidate_path):
            return _agent_failure("the saved result is not a readable PPTX package", evidence)
        evaluate_snapshots, inventory, snapshot_from_dict = _load_runtime()
        try:
            candidate = inventory(candidate_path)
        except ValueError as exc:
            return _agent_failure(f"the saved PPTX is malformed: {{exc}}", evidence)
        plan = json.loads((TEST_ASSETS / "plan.json").read_text(encoding="utf-8"))
        initial = snapshot_from_dict(
            json.loads((TEST_ASSETS / "init_inventory.json").read_text(encoding="utf-8"))
        )
        result = evaluate_snapshots(candidate, initial, plan).to_dict()
        score = float(result["score"])
        if not 0.0 <= score <= 1.0:
            raise RuntimeError(f"evaluator returned an invalid score: {{score}}")
        result.update({{"evaluator": EVALUATOR_ID, "evidence": evidence}})
        return result


TASK_CLASS = {class_name}
'''


def _file_record(
    root: Path,
    path: Path,
    *,
    role: str,
    visibility: str,
    remote_path: str = "",
    vm_path: str = "",
) -> PackageFile:
    return PackageFile(
        role=role,
        relative_path=path.relative_to(root).as_posix(),
        sha256=_sha256(path),
        size=path.stat().st_size,
        visibility=visibility,
        remote_path=remote_path,
        vm_path=vm_path,
    )


def validate_emitted_package(path: str | Path) -> list[str]:
    root = Path(path).resolve()
    issues: list[str] = []
    manifest_path = root / "deployment.json"
    if not manifest_path.is_file():
        return ["deployment package must contain deployment.json"]
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"deployment manifest is unreadable: {exc}"]
    records = manifest.get("files", [])
    if not isinstance(records, list) or not records:
        issues.append("deployment manifest has no files")
        return issues
    seen: set[str] = set()
    public_remote: set[str] = set()
    for record in records:
        relative = str(record.get("relative_path", ""))
        try:
            safe = _safe_relative(relative, "manifest file")
        except AdapterError as exc:
            issues.append(str(exc))
            continue
        folded = safe.as_posix().casefold()
        if folded in seen:
            issues.append(f"duplicate case-insensitive package path: {relative}")
        seen.add(folded)
        file_path = root.joinpath(*safe.parts)
        if not file_path.is_file():
            issues.append(f"manifest file is missing: {relative}")
            continue
        if _sha256(file_path) != record.get("sha256"):
            issues.append(f"manifest hash mismatch: {relative}")
        visibility = record.get("visibility")
        if visibility == "public":
            if file_path.name.casefold() in _RESERVED_PUBLIC_NAMES:
                issues.append(f"hidden evaluator artifact is exposed publicly: {relative}")
            remote = str(record.get("remote_path", ""))
            if not remote:
                issues.append(f"public asset has no remote_path: {relative}")
            elif remote in public_remote:
                issues.append(f"duplicate public remote_path: {remote}")
            public_remote.add(remote)
        elif visibility not in {"hidden", "runner"}:
            issues.append(f"unknown visibility for {relative}: {visibility}")
    module = root / manifest.get("task_module", "")
    if not module.is_file():
        issues.append("task module is missing")
    else:
        try:
            compile(module.read_text(encoding="utf-8"), str(module), "exec")
        except (OSError, SyntaxError) as exc:
            issues.append(f"task module does not compile: {exc}")
    return issues


class DesktopBaseTaskAdapter:
    """Compile a neutral REFRACT bundle for a BaseTask desktop runner."""

    adapter_id = ADAPTER_ID

    def emit(
        self,
        bundle: str | Path,
        output: str | Path,
        profile: RunnerProfile,
        *,
        runner_task_id: str | None = None,
    ) -> EmittedPackage:
        profile = profile.require_valid()
        bundle_root = Path(bundle).resolve()
        bundle_validation = validate_bundle(bundle_root)
        if not bundle_validation.valid:
            raise AdapterError("invalid REFRACT bundle: " + "; ".join(bundle_validation.issues))
        spec = load_task_spec(bundle_root / "task_spec.json").require_valid()
        task_id = runner_task_id or spec.task_id
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{1,79}", task_id):
            raise AdapterError(
                "runner task id must contain 2-80 letters, digits, underscores or hyphens"
            )
        target = Path(output).resolve()
        if target.exists():
            raise AdapterError(f"deployment output already exists: {target}")
        target.parent.mkdir(parents=True, exist_ok=True)
        with _staging_directory(target) as staging:
            task_module = staging / profile.task_class_dir / f"task_{task_id}.py"
            hidden_root = staging / profile.task_assets_dir / f"task_{task_id}" / "tests" / "assets"
            public_root = staging / profile.public_assets_dir / task_id
            manifest_path = staging / "deployment.json"
            records: list[PackageFile] = []

            deck_source = bundle_root / spec.assets["initial_presentation"]
            reference_source = bundle_root / spec.assets["reference_render"]
            if not reference_source.read_bytes().startswith(b"%PDF"):
                raise AdapterError("reference render must be a PDF file")
            deck_public = public_root / "init.pptx"
            reference_public = public_root / "reference.pdf"
            _copy_file(deck_source, deck_public)
            _copy_file(reference_source, reference_public)

            materials_source = bundle_root / spec.assets.get("materials_directory", "materials")
            material_files: list[tuple[Path, PurePosixPath]] = []
            if materials_source.is_dir():
                for source in sorted(materials_source.rglob("*")):
                    if not source.is_file():
                        continue
                    relative = PurePosixPath(source.relative_to(materials_source).as_posix())
                    if source.name.casefold() in _RESERVED_PUBLIC_NAMES:
                        raise AdapterError(
                            f"reserved hidden filename cannot be a material: {relative}"
                        )
                    _copy_file(source, public_root / "materials" / Path(*relative.parts))
                    material_files.append((source, relative))

            plan_source = bundle_root / "evaluator" / "plan.json"
            _copy_file(plan_source, hidden_root / "plan.json")
            initial_inventory = object_inventory(deck_source).to_dict()
            initial_inventory["path"] = "<agent-initial-presentation>"
            _write_json(hidden_root / "init_inventory.json", initial_inventory)
            _runtime_archive(hidden_root / "runtime.zip")

            deck_vm = f"{profile.desktop_dir}/task_{task_id}.pptx"
            reference_vm = f"{profile.desktop_dir}/task_{task_id}_reference.pdf"
            materials_vm = f"{profile.desktop_dir}/task_{task_id}_materials"
            setup_stamp = f"/home/user/.refract_task_{task_id}_setup"
            namespace = _safe_relative(
                profile.public_namespace.format(task_id=task_id), "public_namespace"
            ).as_posix()

            fetch: list[tuple[str, str, str]] = []
            public_specs = [
                (deck_public, "initial_presentation", f"{namespace}/init.pptx", deck_vm),
                (reference_public, "reference_render", f"{namespace}/reference.pdf", reference_vm),
            ]
            for _source, relative in material_files:
                copied = public_root / "materials" / Path(*relative.parts)
                public_specs.append(
                    (
                        copied,
                        "material",
                        f"{namespace}/materials/{relative.as_posix()}",
                        f"{materials_vm}/{relative.as_posix()}",
                    )
                )
            for file_path, role, remote, vm_path in public_specs:
                digest = _sha256(file_path)
                fetch.append((remote, vm_path, digest))
                records.append(
                    _file_record(
                        staging,
                        file_path,
                        role=role,
                        visibility="public",
                        remote_path=remote,
                        vm_path=vm_path,
                    )
                )

            supplied_pptx = frozenset(
                digest
                for remote, _, digest in fetch
                if PurePosixPath(remote).suffix.casefold() == ".pptx"
                and not remote.endswith("/init.pptx")
            )
            final_instruction = _instruction(
                spec.instruction,
                deck_vm,
                reference_vm,
                materials_vm,
                bool(material_files),
            )
            hidden_rel = os.path.relpath(hidden_root, task_module.parent).replace("\\", "/")
            hidden_hashes = {
                name: _sha256(hidden_root / name)
                for name in ("plan.json", "init_inventory.json", "runtime.zip")
            }
            application_command = [
                item.format(deck_path=deck_vm) for item in profile.application_command
            ]
            constants = {
                "TASK_ID": task_id,
                "DECK_NAME": Path(deck_vm).name,
                "DECK_VM_PATH": deck_vm,
                "REFERENCE_VM_PATH": reference_vm,
                "MATERIALS_VM_DIR": materials_vm,
                "DESKTOP_DIR": profile.desktop_dir,
                "SETUP_STAMP": setup_stamp,
                "ASSET_BASE_URL": profile.asset_base_url,
                "ASSET_BASE_ENV": profile.asset_base_env,
                "FETCH": tuple(fetch),
                "INIT_SHA256": _sha256(deck_public),
                "SUPPLIED_PPTX_SHA256": supplied_pptx,
                "HIDDEN_ASSETS_RELATIVE": hidden_rel,
                "HIDDEN_HASHES": hidden_hashes,
                "EVALUATOR_ID": EVALUATOR_ID,
                "INSTRUCTION": final_instruction,
                "SNAPSHOT": profile.snapshot,
                "PLATFORM": profile.platform,
                "RELATED_APPS": list(profile.related_apps),
                "PROXY": profile.proxy,
                "DISABLE_VNC": profile.disable_vnc,
                "DISABLE_RECORDING": profile.disable_recording,
                "VOLUME_SIZE": profile.volume_size,
                "SOURCE": f"{profile.source_label}/{spec.task_id}",
                "APPLICATION_COMMAND": application_command,
                "HAS_MATERIALS": bool(material_files),
            }
            task_module.parent.mkdir(parents=True, exist_ok=True)
            task_module.write_text(_task_source(constants), encoding="utf-8")
            records.append(
                _file_record(staging, task_module, role="task_module", visibility="runner")
            )
            for name in ("plan.json", "init_inventory.json", "runtime.zip"):
                records.append(
                    _file_record(
                        staging,
                        hidden_root / name,
                        role=f"evaluator_{name.rsplit('.', 1)[0]}",
                        visibility="hidden",
                    )
                )

            metadata = {
                "schema_version": "1.0",
                "adapter": ADAPTER_ID,
                "evaluator": EVALUATOR_ID,
                "task_id": task_id,
                "source_task_id": spec.task_id,
                "title": spec.title,
                "instruction": final_instruction,
                "input_file": deck_vm,
                "reference_file": reference_vm,
                "materials_directory": materials_vm if material_files else None,
                "task_fields": {
                    "snapshot": profile.snapshot,
                    "platform": profile.platform,
                    "related_apps": list(profile.related_apps),
                    "intermediate_eval_safe": False,
                    "volume_size": profile.volume_size,
                },
                "runtime_requirements": ["Python 3.11+", "Pillow 10+"],
            }
            metadata_path = staging / profile.task_assets_dir / f"task_{task_id}" / "metadata.json"
            _write_json(metadata_path, metadata)
            records.append(
                _file_record(staging, metadata_path, role="metadata", visibility="hidden")
            )

            package = EmittedPackage(
                package_version="1.0",
                adapter=ADAPTER_ID,
                task_id=task_id,
                root=str(target),
                task_module=task_module.relative_to(staging).as_posix(),
                files=tuple(records),
                instruction=final_instruction,
                profile=profile.to_dict(),
            )
            _write_json(manifest_path, package.to_dict())
            package = EmittedPackage(**{**asdict(package), "files": tuple(records)})
            issues = validate_emitted_package(staging)
            if issues:
                raise AdapterError("deployment package validation failed: " + "; ".join(issues))
            staging.replace(target)
            return package


__all__ = ["DesktopBaseTaskAdapter", "validate_emitted_package"]
